name: Build the website

on:
  workflow_dispatch:
  pull_request:
  merge_group:

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    name: pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  build:
    needs: pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true
          lfs: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build

      - name: Upload site
        uses: actions/upload-artifact@v7
        with:
          name: site
          path: _site
          if-no-files-found: error

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
            source-dir: website/_site
            preview-branch: gh-pages
            umbrella-dir: chapter/pr-preview
            pages-base-path: chapter
            qr-code: true